### PR TITLE
Update with last dev changes

### LINKED ISSUE #6: Fix text header color + search icon when navbartextcolor is change
**Describe the bug**
Color in the header need to be correct 

**To Reproduce**
1. Go to Presentation / theme / Pimenko
2. Edit "navbartextcolor" with #fff
3. Superior texte is blank but text in notification menu too + search icon is always black 

**Expected behavior**
Keep text notification in black
Change search icon with navbartextcolor

**Screenshots**
example

**Desktop (please complete the following information):**
 - All

### LINKED ISSUE #7: Add option to define color of link on hover in header and footer
**Describe the solution you'd like**
As administrator, actually, i can define the color of links in header and footer. 
I want to be able to define the color of links on hover in header and footer.

### PR DESCRIPTION
**Pull request by CrymSonir**
* Add some missing EOL element
* #6 - Fix some element color in header
* #7 - Add option to define a different hoover color for link

Closes #7
Closes #6

### CODE REVIEW

**Comment by m1nhhanh** [comment]
**theme_pimenko | hoovernavbarcolor** works but i dont see **navbartextcolor** anymore?

**Comment by CrymSonir** [comment]
A commit is missing on the branch, will fix it tomorrow

**Comment by CrymSonir** [comment]
@m1nhhanh should be okay now

**Review by m1nhhanh — APPROVED** [review]
Test OK
possible to define for header and footer : 
- color
- text color
- hover text color

**Pull request merged**
